apiVersion: v1
kind: Pod
metadata:
  name: web-server
  # namespace: default
  labels:
    service: web-server
spec:
  containers:
  - name: python-web-server
    image: tachingchen/python-simplehttpserver:0.1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5566
      protocol: TCP
