apiVersion: v1
kind: ConfigMap
metadata:
  name: password
  # namespace: default
data:
  dummy-password: "foobar-password"
---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-2
  # namespace: default
  labels:
    app: nginx
    env: go
spec:
  containers:
    - name: nginx
      image: nginx:1.13
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: config-volume
  volumes:
  - name: config-volume
    configMap:
      name: password
      items:
        - key: dummy-password
          path: index.html
