apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-3
  # namespace: default
  labels:
    env: python
spec:
  containers:
    - name: nginx
      image: nginx:1.13
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          protocol: TCP
      resources:
        requests:
          memory: "128Mi"
          cpu: "128m"
        limits:
          memory: "200Mi"
          cpu: "200m"
