apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  # namespace: default
  labels:
    app: nginx
    backend: python
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx
    ports:
      - containerPort: 80
        protocol: TCP
    volumeMounts:
    - mountPath: /var/log/nginx/
      name: log-volume
  - image: tachingchen/fluentd:0.1
    name: fluentd
    imagePullPolicy: Always
    volumeMounts:
    - mountPath: /var/log/nginx/
      name: log-volume
  volumes:
  - name: log-volume
    emptyDir: {}


