apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  # namespace: default
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30000
  type: NodePort
