apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: default
spec:
  selector:
    service: web-server
  ports:
  - port: 5566
    protocol: TCP
    targetPort: 5566
    nodePort: 30001
  type: NodePort