apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  # namespace: default
spec:
  selector:
    service: reverse-proxy
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
---

# for old k8s cluster:
# apiVersion: extensions/v1beta1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # namespace: default
  labels:
    service: reverse-proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      service: reverse-proxy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: nginx
        service: reverse-proxy
    spec:
      containers:
        - name: nginx
          # For more details of image, please
          # check k8s-workshop/bonus/nginx-pod-3
          image: {{ .Values.nginx.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "128m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          volumeMounts:
          - name: log-volume
            mountPath: /var/log/nginx
      volumes:
      - name: log-volume
        hostPath:
          # directory location on host
          path: /var/log/k8s-daemonset/nginx/
          # this field is optional
          # DirectoryOrCreate: create directory if not present
          type: DirectoryOrCreate

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
  # namespace: default
spec:
  minReplicas: {{ .Values.nginx.minReplicas }}
  maxReplicas: {{ .Values.nginx.maxReplicas }}
  scaleTargetRef:
    # for old k8s cluster:
    # apiVersion: extensions/v1beta1
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  targetCPUUtilizationPercentage: {{ .Values.nginx.hpaCPU }}
